### ISSUE TITLE
400 bad request happened when hit /u/api/notification

### ISSUE THREAD

**Issue by konpyu** [shumipro/meetapp#38]
### reproduce
Login via facebook then visit any page

### problem
I got 400 error with alert 

![sc 2015-05-10 21 36 58](https://cloud.githubusercontent.com/assets/997966/7554290/b0f5dfb2-f75c-11e4-92c8-483573ac6e6a.png)

I suspect Kon's user data has unexpected part or broken.

**Comment by tejitak** [comment]
Hi,
Thank you for reporting it!
We'll fix it soon

**Comment by tejitak** [comment]
It looks fixed. I close the issue. 
Please feel free to reopen it if the issue still occurs.

**Comment by konpyu** [comment]
Thanks! alert has disappeared
