### ISSUE TITLE
Uploaing app cover image is failed

### ISSUE THREAD

**Issue by konpyu** [shumipro/meetapp#69]
I tried uploading cover image but it failed.
I suspect converting image process was aborted because url has no ext(ex: png, jpg)

![sc 2015-05-20 10 20 38](https://cloud.githubusercontent.com/assets/997966/7717340/b5cb157c-feda-11e4-859d-cf330cadee28.png)

image file is here
https://tokyotownname.s3.amazonaws.com/uploads/image/image/284/pickup_DSC01874.JPG

**Comment by tejitak** [comment]
Thank you for reporting it. 
It seems uploading any images are now failed. We are investigating.

**Comment by tejitak** [comment]
Thanks to @kyokomi , the issue has been resolved. I close the issue.

**Comment by konpyu** [comment]
cooooooooooooool!
