### ISSUE TITLE
OG setting for app detail page

### ISSUE THREAD

**Issue by konpyu** [shumipro/meetapp#72]
It is more preferable that app-detail page og has its specific info when sharing FB.

`og:title` `og:image` `og:url` `og:description`

![sc 2015-05-20 12 45 07](https://cloud.githubusercontent.com/assets/997966/7718600/1fc71ae4-feee-11e4-85cd-1650d98bedd0.png)

**Comment by tejitak** [comment]
![2015-05-20 20 42 06](https://cloud.githubusercontent.com/assets/5313274/7724923/b67bda78-ff30-11e4-8e8e-32786a8f951d.png)

Hi @konpyu ,
Now looks fine. Please check it.

**Comment by konpyu** [comment]
@tejitak 
looks good. Thank you for implement!
