### ISSUE TITLE
バグかもしれないレポート

### ISSUE THREAD

**Issue by yasunobuigarashi** [shumipro/meetapp#82]
１．OSSコードリーダーでスターを押したら、マイページに飛んだ　（←　バグかも）
２．OSSコードリーダーに戻ってスターを押したら、自分のスターがついた
３．OSSコードリーダーではずすを押したら、自分でない他の人のスターが消えた　（←バグかも。誰のスターかはわからず、自分がはずすを押す前のスクリーンキャプチャを取っていた訳ではないので記憶違いかもしれません）
４．OSSコードリーダーではずすを押したら、自分のスターが消えた
５．OSSコードリーダーでに戻ってスターを押したら、自分のスターがついた

**Comment by tejitak** [comment]
ありがとうございます。調査します！

**Comment by tejitak** [comment]
1に関しては今はログイン後に必ずマイページに飛んでしまう実装になっているので、そちらは改善案として登録しておきます。
3の他人のスターが消えてしまう件は直っていると思います！ご確認お願いします

**Comment by yasunobuigarashi** [comment]
修正ありがとうございました！
