### ISSUE TITLE
「開発に興味あり」のバグかもしれません

### ISSUE THREAD

**Issue by yasunobuigarashi** [shumipro/meetapp#85]
週末も開発お疲れ様です。
meetappはすごく面白そうなのでいじっていたのですが
またバグっぽいのをみつけたので報告します。

１．開発に興味ありを押す
２．ダイアログが表示
３．OKを押す
４．もう一度同じダイアログが表示される　←　バグかもしれない
５．OKを押す
６．ダイアログが消える

当方、windows8 + Chrome バージョン 43.0.2357.124 m です。
お時間つくれたときに、ご確認頂ければ幸いです。

**Comment by tejitak** [comment]
@yasunobuigarashi さん、
いじってくれてありがとうございますm(_ _)m
おそらく上記の現象は1回目の通信のresponseの前にもう一つrequestが飛んでしまったのではないかと思い、連打防止策を入れました。現在は治っていると思います。お時間のあるときに、ご確認くださいませ。

(一応、現在は実装の簡略化のためもあり、「興味あり」ボタンは何度も押せる仕様となっております)

**Comment by yasunobuigarashi** [comment]
はい、私のマウスが調子悪くて連打状態になったいたのが問題だったと思います。
変なエラー出してすみません w
ご対応ありがとうございました
